server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    username: ""
    password: ""
    url: "jdbc:h2:./devDatabase"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

logging:
  level:
    root: INFO
    web: DEBUG