server:
  port: ${PORT:5000}

base-url: /api

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger.html